name: JobQueueSystem

x-LoggingSettings: &loggingSettings
  Logging__LogLevel__Default: Trace
  Logging__LogLevel__Microsoft: Information
  Logging__LogLevel__Microsoft_Hosting_Lifetime: Information

x-LogSerilogSettings: &logCommonSerilogSettings
  Serilog__MinimumLevel__Default: Debug
  Serilog__MinimumLevel__Override__Microsoft: Information
  Serilog__WriteTo__1__Args__nodeUris: http://elasticsearch:9200
  Serilog__WriteTo__1__Args__indexFormat: job-queue-system-{0:yyyy.MM.dd}
 
x-AuthOptionsConfig: &authOptionsConfig
  ApplicationSettings__AuthOptions__Authority: ${KEYCLOAK_HOSTNAME}
  # ClientId for a frontend application
  ApplicationSettings__AuthOptions__Audiences__0: ${AUTH_FRONTEND_CLIENT_ID}
  # ClientId for backend services
  ApplicationSettings__AuthOptions__Audiences__1: ${AUTH_SERVICES_CLIENT_ID}
  ApplicationSettings__AuthOptions__RequireHttpsMetadata: "false"
  ApplicationSettings__AuthOptions__Realm: ${AUTH_REALM}

x-RabbitMQConfig: &rabbitMQConfig
  ApplicationSettings__RabbitConfig__User: guest
  ApplicationSettings__RabbitConfig__Password: guest
  ApplicationSettings__RabbitConfig__Host: rabbitmq

x-JobRepositoryServiceClient: &jobRepositoryServiceClient
  ApplicationSettings__JobRepositoryClientConfig__BaseUrl: http://job-repository-service:8000
  ApplicationSettings__JobRepositoryClientConfig__AuthClientCredentials__ClientId: ${AUTH_SERVICES_CLIENT_ID}
  ApplicationSettings__JobRepositoryClientConfig__AuthClientCredentials__ClientSecret: ${AUTH_CLIENT_SECRET}
  ApplicationSettings__JobRepositoryClientConfig__AuthClientCredentials__Authority: http://keycloak:8080
  ApplicationSettings__JobRepositoryClientConfig__AuthClientCredentials__Realm: ${AUTH_REALM}
      
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:16.10-alpine3.21
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    command: start
    environment:
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
        - postgres

  mongodb:
    image: mongo:noble
    volumes:
        - mongo_db://data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  job-manager-react-app:
    image: job-manager-react-app:latest
    build:
      context: .
      dockerfile: JobManagerReactApp/Dockerfile
    ports:
     - "8000:80"
    environment:
      VITE_API_BASE_URL: /api
      VITE_JOB_PRODUCER_API: /JobPublisher
      VITE_ODATA_URL: /odata
      VITE_KEYCLOAK_ENDPOINT: ${KEYCLOAK_HOSTNAME}
      VITE_KEYCLOAK_REALM: ${AUTH_REALM}
      VITE_KEYCLOAK_CLIENT_ID: ${AUTH_FRONTEND_CLIENT_ID}
    restart: always
    extra_hosts:
    # To allow services to reach Keycloak on host machine during development
    - "localhost:host-gateway"
    depends_on:
      - keycloak
      - job-repository-service
      - job-producer-service
      
  job-repository-service:
    image: job-repository-service:latest
    build:
      context: .
      dockerfile: JobRepositoryService/Dockerfile
    ports:
     - "8001:8000"
    environment:
      ASPNETCORE_URLS: http://+:8000
      Logging__LogLevel__Microsoft.AspNetCore.Authentication: Debug
      Logging__LogLevel__Microsoft.IdentityModel: Debug
      ApplicationSettings__ConnectionString: mongodb://mongodb:27017
      ApplicationSettings__Database: JobQueueSystem
      <<: [*authOptionsConfig,*loggingSettings,*logCommonSerilogSettings]
    restart: always
    extra_hosts:
    # To allow services to reach Keycloak on host machine during development
    - "localhost:host-gateway"
    depends_on:
      - mongodb
      - keycloak
    
  job-producer-service:
    image: job-producer-service:latest
    build:
      context: .
      dockerfile: JobProducerService/Dockerfile
    ports:
     - "8002:8000"
    environment:
      ASPNETCORE_URLS: http://+:8000
      ApplicationSettings__RabbitConfig__QueueName: job-request-queue
      <<: [*rabbitMQConfig, *authOptionsConfig, *jobRepositoryServiceClient, *logCommonSerilogSettings]
    restart: always
    extra_hosts:
    # To allow services to reach Keycloak on host machine during development
    - "localhost:host-gateway"
    depends_on:
      - job-repository-service
      - rabbitmq
      - keycloak 
  
  job-request-receiver-service:
    image: job-request-receiver-service:latest
    build:
      context: .
      dockerfile: JobRequestReceiverService/Dockerfile
    environment:
      ApplicationSettings__RabbitConfig__QueueName: job-request-queue
      <<: [*rabbitMQConfig,*jobRepositoryServiceClient,*logCommonSerilogSettings]
    restart: always
    depends_on:
      - job-repository-service
      - rabbitmq
      - keycloak

  job-dispatcher-service:
    image: job-dispatcher-service:latest
    build:
      context: .
      dockerfile: JobDispatcherService/Dockerfile
    environment:
      <<: [*rabbitMQConfig, *jobRepositoryServiceClient, *logCommonSerilogSettings]
    restart: always
    depends_on:
      - job-repository-service
      - rabbitmq
      - keycloak

  job-handlers:
    image: job-handlers:latest
    build:
      context: .
      dockerfile: JobHandlers/Dockerfile
    environment:
      << : [*loggingSettings, *logCommonSerilogSettings, *rabbitMQConfig, *jobRepositoryServiceClient]
    restart: always
    depends_on:
      - job-repository-service
      - rabbitmq
      - keycloak
volumes:
  # Volume for PostgreSQL data persistence
  postgres_data:
    driver: local
  # Volume for Elasticsearch data persistence
  esdata:
    driver: local
  # Volume for MongoDB data persistence
  mongo_db:
    driver: local