/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/JobsRepository/job-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;odata.metadata=minimal;odata.streaming=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=minimal;odata.streaming=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=minimal": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=full;odata.streaming=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=full;odata.streaming=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=full": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=none;odata.streaming=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=none;odata.streaming=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=none": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.streaming=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.streaming=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=minimal;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=minimal;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=full;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=full;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=none;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.metadata=none;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;IEEE754Compatible=false": components["schemas"]["JobTypeDescriptor"][];
                        "application/json;IEEE754Compatible=true": components["schemas"]["JobTypeDescriptor"][];
                        "application/xml": components["schemas"]["JobTypeDescriptor"][];
                        "text/plain": components["schemas"]["JobTypeDescriptor"][];
                        "application/octet-stream": components["schemas"]["JobTypeDescriptor"][];
                        "text/json": components["schemas"]["JobTypeDescriptor"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/JobsRepository": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;odata.metadata=minimal;odata.streaming=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=minimal;odata.streaming=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=minimal": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=full;odata.streaming=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=full;odata.streaming=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=full": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=none;odata.streaming=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=none;odata.streaming=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=none": components["schemas"]["JobInfo"][];
                        "application/json;odata.streaming=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.streaming=false": components["schemas"]["JobInfo"][];
                        "application/json": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=minimal;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=minimal;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=full;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=full;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=none;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.metadata=none;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/json;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/json;IEEE754Compatible=false": components["schemas"]["JobInfo"][];
                        "application/json;IEEE754Compatible=true": components["schemas"]["JobInfo"][];
                        "application/xml": components["schemas"]["JobInfo"][];
                        "text/plain": components["schemas"]["JobInfo"][];
                        "application/octet-stream": components["schemas"]["JobInfo"][];
                        "text/json": components["schemas"]["JobInfo"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;odata.metadata=minimal;odata.streaming=true": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=minimal;odata.streaming=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=minimal": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=full;odata.streaming=true": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=full;odata.streaming=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=full": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=none;odata.streaming=true": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=none;odata.streaming=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=none": components["schemas"]["JobRequest"];
                    "application/json;odata.streaming=true": components["schemas"]["JobRequest"];
                    "application/json;odata.streaming=false": components["schemas"]["JobRequest"];
                    "application/json": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=minimal;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=minimal;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=full;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=full;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=none;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;odata.metadata=none;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/json;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/json;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/json;IEEE754Compatible=false": components["schemas"]["JobRequest"];
                    "application/json;IEEE754Compatible=true": components["schemas"]["JobRequest"];
                    "application/xml": components["schemas"]["JobRequest"];
                    "text/plain": components["schemas"]["JobRequest"];
                    "text/json": components["schemas"]["JobRequest"];
                    "application/*+json": components["schemas"]["JobRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/JobsRepository/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;odata.metadata=minimal;odata.streaming=true": components["schemas"]["Job"];
                        "application/json;odata.metadata=minimal;odata.streaming=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=minimal": components["schemas"]["Job"];
                        "application/json;odata.metadata=full;odata.streaming=true": components["schemas"]["Job"];
                        "application/json;odata.metadata=full;odata.streaming=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=full": components["schemas"]["Job"];
                        "application/json;odata.metadata=none;odata.streaming=true": components["schemas"]["Job"];
                        "application/json;odata.metadata=none;odata.streaming=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=none": components["schemas"]["Job"];
                        "application/json;odata.streaming=true": components["schemas"]["Job"];
                        "application/json;odata.streaming=false": components["schemas"]["Job"];
                        "application/json": components["schemas"]["Job"];
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/json;odata.metadata=minimal;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=minimal;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/json;odata.metadata=full;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=full;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=none;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;odata.metadata=none;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/json;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/json;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/json;IEEE754Compatible=false": components["schemas"]["Job"];
                        "application/json;IEEE754Compatible=true": components["schemas"]["Job"];
                        "application/xml": components["schemas"]["Job"];
                        "text/plain": components["schemas"]["Job"];
                        "application/octet-stream": components["schemas"]["Job"];
                        "text/json": components["schemas"]["Job"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;odata.metadata=minimal;odata.streaming=true": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false": number;
                        "application/json;odata.metadata=minimal": number;
                        "application/json;odata.metadata=full;odata.streaming=true": number;
                        "application/json;odata.metadata=full;odata.streaming=false": number;
                        "application/json;odata.metadata=full": number;
                        "application/json;odata.metadata=none;odata.streaming=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false": number;
                        "application/json;odata.metadata=none": number;
                        "application/json;odata.streaming=true": number;
                        "application/json;odata.streaming=false": number;
                        "application/json": number;
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=minimal;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;IEEE754Compatible=true": number;
                        "application/json;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;IEEE754Compatible=false": number;
                        "application/json;IEEE754Compatible=true": number;
                        "application/xml": number;
                        "text/plain": number;
                        "application/octet-stream": number;
                        "text/json": number;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/JobsRepository/{jobId}/SetStatus/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                    status: components["schemas"]["JobStatus"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;odata.metadata=minimal;odata.streaming=true": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false": number;
                        "application/json;odata.metadata=minimal": number;
                        "application/json;odata.metadata=full;odata.streaming=true": number;
                        "application/json;odata.metadata=full;odata.streaming=false": number;
                        "application/json;odata.metadata=full": number;
                        "application/json;odata.metadata=none;odata.streaming=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false": number;
                        "application/json;odata.metadata=none": number;
                        "application/json;odata.streaming=true": number;
                        "application/json;odata.streaming=false": number;
                        "application/json": number;
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=minimal;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;IEEE754Compatible=true": number;
                        "application/json;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;IEEE754Compatible=false": number;
                        "application/json;IEEE754Compatible=true": number;
                        "application/xml": number;
                        "text/plain": number;
                        "application/octet-stream": number;
                        "text/json": number;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/JobsRepository/{jobId}/SetResult": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;odata.metadata=minimal;odata.streaming=true": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=minimal;odata.streaming=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=minimal": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=full;odata.streaming=true": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=full;odata.streaming=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=full": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=none;odata.streaming=true": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=none;odata.streaming=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=none": components["schemas"]["JobPayload"];
                    "application/json;odata.streaming=true": components["schemas"]["JobPayload"];
                    "application/json;odata.streaming=false": components["schemas"]["JobPayload"];
                    "application/json": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=minimal;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=minimal;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=full;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=full;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=none;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;odata.metadata=none;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/json;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/json;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/json;IEEE754Compatible=false": components["schemas"]["JobPayload"];
                    "application/json;IEEE754Compatible=true": components["schemas"]["JobPayload"];
                    "application/xml": components["schemas"]["JobPayload"];
                    "text/plain": components["schemas"]["JobPayload"];
                    "text/json": components["schemas"]["JobPayload"];
                    "application/*+json": components["schemas"]["JobPayload"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;odata.metadata=minimal;odata.streaming=true": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false": number;
                        "application/json;odata.metadata=minimal": number;
                        "application/json;odata.metadata=full;odata.streaming=true": number;
                        "application/json;odata.metadata=full;odata.streaming=false": number;
                        "application/json;odata.metadata=full": number;
                        "application/json;odata.metadata=none;odata.streaming=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false": number;
                        "application/json;odata.metadata=none": number;
                        "application/json;odata.streaming=true": number;
                        "application/json;odata.streaming=false": number;
                        "application/json": number;
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=minimal;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;IEEE754Compatible=true": number;
                        "application/json;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;IEEE754Compatible=false": number;
                        "application/json;IEEE754Compatible=true": number;
                        "application/xml": number;
                        "text/plain": number;
                        "application/octet-stream": number;
                        "text/json": number;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/JobsRepository/{jobId}/SetErrorResult": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;odata.metadata=minimal;odata.streaming=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=minimal;odata.streaming=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=minimal": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=full;odata.streaming=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=full;odata.streaming=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=full": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=none;odata.streaming=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=none;odata.streaming=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=none": components["schemas"]["ErrorPayload"];
                    "application/json;odata.streaming=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.streaming=false": components["schemas"]["ErrorPayload"];
                    "application/json": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=minimal;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=minimal;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=full;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=full;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=none;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.metadata=none;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/json;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/json;IEEE754Compatible=false": components["schemas"]["ErrorPayload"];
                    "application/json;IEEE754Compatible=true": components["schemas"]["ErrorPayload"];
                    "application/xml": components["schemas"]["ErrorPayload"];
                    "text/plain": components["schemas"]["ErrorPayload"];
                    "text/json": components["schemas"]["ErrorPayload"];
                    "application/*+json": components["schemas"]["ErrorPayload"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;odata.metadata=minimal;odata.streaming=true": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false": number;
                        "application/json;odata.metadata=minimal": number;
                        "application/json;odata.metadata=full;odata.streaming=true": number;
                        "application/json;odata.metadata=full;odata.streaming=false": number;
                        "application/json;odata.metadata=full": number;
                        "application/json;odata.metadata=none;odata.streaming=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false": number;
                        "application/json;odata.metadata=none": number;
                        "application/json;odata.streaming=true": number;
                        "application/json;odata.streaming=false": number;
                        "application/json": number;
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=minimal;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=minimal;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=full;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=full;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;IEEE754Compatible=false": number;
                        "application/json;odata.metadata=none;IEEE754Compatible=true": number;
                        "application/json;odata.streaming=true;IEEE754Compatible=false": number;
                        "application/json;odata.streaming=true;IEEE754Compatible=true": number;
                        "application/json;odata.streaming=false;IEEE754Compatible=false": number;
                        "application/json;odata.streaming=false;IEEE754Compatible=true": number;
                        "application/json;IEEE754Compatible=false": number;
                        "application/json;IEEE754Compatible=true": number;
                        "application/xml": number;
                        "text/plain": number;
                        "application/octet-stream": number;
                        "text/json": number;
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Odata/$metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Odata/$metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Odata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Odata/"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Attachment: {
            id?: string | null;
            fileName?: string | null;
            contentType?: string | null;
            /** Format: int64 */
            size?: number;
        };
        /** @enum {string} */
        EdmContainerElementKind: "None" | "EntitySet" | "ActionImport" | "FunctionImport" | "Singleton";
        /** @enum {string} */
        EdmExpressionKind: "None" | "BinaryConstant" | "BooleanConstant" | "DateTimeOffsetConstant" | "DecimalConstant" | "FloatingConstant" | "GuidConstant" | "IntegerConstant" | "StringConstant" | "DurationConstant" | "Null" | "Record" | "Collection" | "Path" | "If" | "Cast" | "IsOf" | "FunctionApplication" | "LabeledExpressionReference" | "Labeled" | "PropertyPath" | "NavigationPropertyPath" | "DateConstant" | "TimeOfDayConstant" | "EnumMember" | "AnnotationPath";
        /** @enum {string} */
        EdmSchemaElementKind: "None" | "TypeDefinition" | "Term" | "Action" | "EntityContainer" | "Function";
        /** @enum {string} */
        EdmTypeKind: "None" | "Primitive" | "Entity" | "Complex" | "Collection" | "EntityReference" | "Enum" | "TypeDefinition" | "Untyped" | "Path";
        ErrorPayload: {
            errorMessage?: string | null;
        };
        IEdmDirectValueAnnotationsManager: Record<string, never>;
        IEdmEntityContainer: {
            readonly elements?: components["schemas"]["IEdmEntityContainerElement"][] | null;
            schemaElementKind?: components["schemas"]["EdmSchemaElementKind"];
            readonly namespace?: string | null;
            readonly name?: string | null;
        };
        IEdmEntityContainerElement: {
            containerElementKind?: components["schemas"]["EdmContainerElementKind"];
            container?: components["schemas"]["IEdmEntityContainer"];
            readonly name?: string | null;
        };
        IEdmExpression: {
            expressionKind?: components["schemas"]["EdmExpressionKind"];
        };
        IEdmModel: {
            readonly schemaElements?: components["schemas"]["IEdmSchemaElement"][] | null;
            readonly vocabularyAnnotations?: components["schemas"]["IEdmVocabularyAnnotation"][] | null;
            readonly referencedModels?: components["schemas"]["IEdmModel"][] | null;
            readonly declaredNamespaces?: string[] | null;
            directValueAnnotationsManager?: components["schemas"]["IEdmDirectValueAnnotationsManager"];
            entityContainer?: components["schemas"]["IEdmEntityContainer"];
        };
        IEdmSchemaElement: {
            schemaElementKind?: components["schemas"]["EdmSchemaElementKind"];
            readonly namespace?: string | null;
            readonly name?: string | null;
        };
        IEdmTerm: {
            type?: components["schemas"]["IEdmTypeReference"];
            readonly appliesTo?: string | null;
            readonly defaultValue?: string | null;
            schemaElementKind?: components["schemas"]["EdmSchemaElementKind"];
            readonly namespace?: string | null;
            readonly name?: string | null;
        };
        IEdmType: {
            typeKind?: components["schemas"]["EdmTypeKind"];
        };
        IEdmTypeReference: {
            readonly isNullable?: boolean;
            definition?: components["schemas"]["IEdmType"];
        };
        IEdmVocabularyAnnotatable: Record<string, never>;
        IEdmVocabularyAnnotation: {
            readonly qualifier?: string | null;
            term?: components["schemas"]["IEdmTerm"];
            target?: components["schemas"]["IEdmVocabularyAnnotatable"];
            value?: components["schemas"]["IEdmExpression"];
            readonly usesDefault?: boolean;
        };
        Job: {
            type?: components["schemas"]["JobType"];
            status?: components["schemas"]["JobStatus"];
            /** Format: date-time */
            lastStatusChanged?: string | null;
            /** Format: date-time */
            receivedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            /** Format: uuid */
            jobId?: string;
            isSuccess?: boolean | null;
            errorMessage?: string | null;
            requestPayload?: components["schemas"]["JobPayload"];
            resultPayload?: components["schemas"]["JobResult"];
        };
        JobInfo: {
            type?: components["schemas"]["JobType"];
            status?: components["schemas"]["JobStatus"];
            /** Format: date-time */
            lastStatusChanged?: string | null;
            /** Format: date-time */
            receivedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            /** Format: uuid */
            jobId?: string;
            isSuccess?: boolean | null;
            errorMessage?: string | null;
        };
        JobPayload: {
            data?: string | null;
            attachment?: components["schemas"]["Attachment"];
        };
        JobRequest: {
            /** Format: uuid */
            jobId?: string;
            type?: components["schemas"]["JobType"];
            payload?: components["schemas"]["JobPayload"];
        };
        JobResult: {
            payload?: components["schemas"]["JobPayload"];
            isSuccess?: boolean | null;
            errorMessage?: string | null;
        };
        /** @enum {string} */
        JobStatus: "NotStarted" | "Enqueued" | "InProgress" | "Failed" | "Finished";
        /** @enum {string} */
        JobType: "Dummy" | "ConvertWordToPdf" | "ConvertHtmlToPdf" | "ConvertExcelToPdf" | "ConvertScanToSearchablePdf";
        JobTypeDescriptor: {
            jobType?: components["schemas"]["JobType"];
            description?: string | null;
        };
        ODataEntitySetInfo: {
            typeAnnotation?: components["schemas"]["ODataTypeAnnotation"];
            /** Format: uri */
            url?: string | null;
            name?: string | null;
            title?: string | null;
        };
        ODataFunctionImportInfo: {
            typeAnnotation?: components["schemas"]["ODataTypeAnnotation"];
            /** Format: uri */
            url?: string | null;
            name?: string | null;
            title?: string | null;
        };
        ODataServiceDocument: {
            typeAnnotation?: components["schemas"]["ODataTypeAnnotation"];
            entitySets?: components["schemas"]["ODataEntitySetInfo"][] | null;
            singletons?: components["schemas"]["ODataSingletonInfo"][] | null;
            functionImports?: components["schemas"]["ODataFunctionImportInfo"][] | null;
        };
        ODataSingletonInfo: {
            typeAnnotation?: components["schemas"]["ODataTypeAnnotation"];
            /** Format: uri */
            url?: string | null;
            name?: string | null;
            title?: string | null;
        };
        ODataTypeAnnotation: {
            typeName?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "Odata/$metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;odata.metadata=minimal;odata.streaming=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=minimal;odata.streaming=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=minimal": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=full;odata.streaming=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=full;odata.streaming=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=full": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=none;odata.streaming=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=none;odata.streaming=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=none": components["schemas"]["IEdmModel"];
                    "application/json;odata.streaming=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.streaming=false": components["schemas"]["IEdmModel"];
                    "application/json": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=minimal;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=minimal;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=full;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=full;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=none;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.metadata=none;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/json;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/json;IEEE754Compatible=false": components["schemas"]["IEdmModel"];
                    "application/json;IEEE754Compatible=true": components["schemas"]["IEdmModel"];
                    "application/xml": components["schemas"]["IEdmModel"];
                    "text/plain": components["schemas"]["IEdmModel"];
                    "application/octet-stream": components["schemas"]["IEdmModel"];
                    "text/json": components["schemas"]["IEdmModel"];
                };
            };
        };
    };
    "Odata/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;odata.metadata=minimal;odata.streaming=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=minimal;odata.streaming=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=minimal": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=full;odata.streaming=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=full;odata.streaming=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=full": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=none;odata.streaming=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=none;odata.streaming=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=none": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.streaming=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.streaming=false": components["schemas"]["ODataServiceDocument"];
                    "application/json": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=minimal;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=minimal;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=full;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=full;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=none;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=none;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=none;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.metadata=none;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.streaming=true;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.streaming=true;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.streaming=false;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;odata.streaming=false;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/json;IEEE754Compatible=false": components["schemas"]["ODataServiceDocument"];
                    "application/json;IEEE754Compatible=true": components["schemas"]["ODataServiceDocument"];
                    "application/xml": components["schemas"]["ODataServiceDocument"];
                    "text/plain": components["schemas"]["ODataServiceDocument"];
                    "application/octet-stream": components["schemas"]["ODataServiceDocument"];
                    "text/json": components["schemas"]["ODataServiceDocument"];
                };
            };
        };
    };
}
